check if borg is actually installed

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -2,6 +2,9 @@
 
 die(){ echo "$*" >&2; exit 1; }
 
+command -v borg &>/dev/null \
+	|| die 'Cannot find borg executable!'
+
 BACKUP_CONF="${BACKUP_CONF:-default}"
 
 if [ -r "$HOME/.config/backup/${BACKUP_CONF}.env" ]; then
