fix tilde usage

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -4,8 +4,8 @@ die(){ echo "$*" >&2; exit 1; }
 
 BACKUP_CONF="${BACKUP_CONF:-default}"
 
-if [ -r "~/.config/backup/${BACKUP_CONF}.env" ]; then
-	. "~/.config/backup/${BACKUP_CONF}.env" || die "Could not read envfile."
+if [ -r "$HOME/.config/backup/${BACKUP_CONF}.env" ]; then
+	. "$HOME/.config/backup/${BACKUP_CONF}.env" || die "Could not read envfile."
 elif [ -r "/etc/backup/${BACKUP_CONF}.env" ]; then
 	. "/etc/backup/${BACKUP_CONF}.env" || die "Could not read envfile."
 else
